name: Build.NET Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore .NET dependencies
      run: dotnet restore
    - name: Build Soulution
      run: dotnet build --no-restore
    - name: Run unit Test
      run: dotnet test --no-build --verbosity normal
